default:
  image: ruby:latest

.pages:
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
    BUNDLE_PATH: .gem
  cache:
    key: bundler-cache
    paths:
      - $BUNDLE_PATH
  before_script:
    - bundle install
  script:
    - bundle exec jekyll build -d public
  only:
    changes:
      - _data/**/*
      - _includes/**/*
      - _pages/**/*
      - _posts/**/*
      - _sass/**/*
      - assets/**/*
      - "*.png"
      - _config.yml
      - browserconfig.xml
      - favicon.ico
      - Gemfile
      - Gemfile.lock
      - index.md
      - safari-pinned-tab.svg
      - site.webmanifest
      - staticman.yml

pages:
  extends: .pages
  stage: deploy
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    refs:
      - main

test_pages:
  extends: .pages
  stage: test
  only:
    refs:
      - merge_requests
