# Check links in text files
# https://github.com/dkhamsing/awesome_bot

# Ruby gem method
.gem:
  image: ruby:latest
  before_script:
    - gem install awesome_bot

# Docker method
.docker:
  image: dkhamsing/awesome_bot

# use either `extends: .gem` or `extends: .docker`
test:
  extends: .gem
  # extends: .docker
  script:
    - "awesome_bot --allow-dupe --skip-save-results --white-list
      stackexchange.com,\
      stackoverflow.com,\
      askubuntu.com,\
      superuser.com
      `find . -name '*.md'`"
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.md"
