name: py-geo
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3
  - geopandas
  - rioxarray
  - rasterstats
  - scipy
  - cfgrib
  - netcdf4
  - cdo  # unavailable on Windows; use Conda with WSL
  - dask  # parallel computing
  - pooch  # to download data
  - matplotlib  # plotting tools
  - matplotlib_scalebar
  - nc-time-axis
  - seaborn
  - cartopy
  - mapclassify
  - contextily
  - pyviz
  - hvplot
  - jupyterlab  # interactive notebooks
  - jupyter_bokeh
  - pytest  # testing and linting
  - flake8
  - pylint
  - black
  - black-jupyter
