name: r-geo
channels:
  - conda-forge
  - r
  - anaconda
dependencies:
  - r-base
  - r-essentials
  - libgit2  # to install packages from Git repositories
  - r-devtools
  - r-terra
  - r-rgdal
  - r-sf
  - r-geojsonio
  - r-rgeos
  - r-rastervis
  - jupyterlab
