// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("extensions.zotero.automaticSnapshots", false);
user_pref("extensions.zotero.dataDir", "~/Zotero");
user_pref("extensions.zotero.export.quickCopy.setting", "bibliography=the-open-university-harvard-modded");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":false,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"keepUpdated\":true,\"worker\":true,\"includeAnnotations\":false}");
user_pref("extensions.zotero.fileHandler.pdf", "/bin/okular");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "authEtal2.lower + year.prefix(_)");
user_pref("extensions.zotero.translators.better-bibtex.exportTitleCase", false);
user_pref("extensions.zotero.translators.better-bibtex.importSentenceCase", "off");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.translators.better-bibtex.skipFields", "abstract,shorttitle,keywords,file,annotation");
user_pref("extensions.zotero.translators.better-bibtex.warnBulkModify", 0);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("extensions.zotfile.authors_delimiter", ".");
user_pref("extensions.zotfile.dest_dir", "/run/media/nms/Backup/Documents/Zotero");
user_pref("extensions.zotfile.etal", ".etal");
user_pref("extensions.zotfile.import", false);
user_pref("extensions.zotfile.max_titlelength", 50);
user_pref("extensions.zotfile.replace_blanks", true);
user_pref("extensions.zotfile.source_dir", "/run/media/nms/Backup/Documents/Zotero");
user_pref("extensions.zotfile.source_dir_ff", false);
user_pref("intl.accept_languages", "en-GB, en");
